JKCS4 &  5

diff --git a/TOOLS/MANIPULATE/JKname b/TOOLS/MANIPULATE/JKname
--- a/TOOLS/MANIPULATE/JKname
+++ b/TOOLS/MANIPULATE/JKname
@@ -11,22 +11,22 @@ function help {
     - if file.xyz exist, then create file-#.xyz, where # is increasing nnumber
 
   OPTIONS:
-    -log ...... use .log instead if .xyz (convert first .log to .xyz)
+    -mol MOL NAME . predefine your molecule (MOL = atoms summary, eg.: CxOyHz)
+    -log .......... use .log instead if .xyz (convert first .log to .xyz)
     OTHERS: -hom, -msa, -buoh
 
   EXAMPLES:
     JKname 
-    JKname -log
-    JKname 123.xyz
+    JKname -log -msa
+    JKname 123.xyz -mol C2H6O1 EtOH 
     JKname -log 123.log 234.log
   """
   exit
 }
-Qmsa=0
-Qhom=0
-Qbuoh=0
-FILES=""
 
+usermolecules=""
+usermoleculesN=""
+FILES=""
 Qlog=0
 next=0
 for i in $*
@@ -37,28 +37,118 @@ do
   then
     if [ "$i" == "-hom" ]
     then
-      Qhom=1
+      usermolecules+=" C10O8H16" 
+      usermoleculesN+=" hom"
       continue
     fi
     if [ "$i" == "-msa" ]
     then
-      Qmsa=1
+      usermolecules+=" S1O3H1C1H3" 
+      usermoleculesN+=" msa"
       continue
     fi
     if [ "$i" == "-buoh" ]
     then
-      Qbuoh=1
+      usermolecules+=" C4O1H10" 
+      usermoleculesN+=" buoh"
       continue
     fi
+    ###
+    if [ "$i" == "-mol" ]
+    then
+      next=1
+      last="-mol"
+      continue
+    fi
+    if [ "$last" == "-mol" ]
+    then
+      last="-mol2"
+      usermolecules+=" $i"
+      continue
+    fi
+    if [ "$last" == "-mol2" ]
+    then
+      last=""
+      next=0
+      usermoleculesN+=" $i"
+      continue
+    fi
+    ###
     if [ "$i" == "-log" ]
     then
       Qlog=1
       continue
     fi
+  else
+    files+=" $i"
   fi
-  files+=" $i"
 done
 
+
+###############################################################
+### FUNCTIONS ####
+
+function molcheck {
+  min=""
+  guessatoms=`echo $1 | sed "s/[0-9]/ /g"`  
+  guessnums=` echo $1 | sed "s/[a-z]/ /g" | sed "s/[A-Z]/ /g"`  
+  #check size
+  countatoms=`echo $guessatoms |  xargs -n 1 |  wc -l`
+  countnums=`echo  $guessnums  |  xargs -n 1 |  wc -l`
+  if [ $countatoms -ne $countnums ]
+  then
+    echo "JKname: Wrong input: $1 [EXITING]"
+    exit
+  fi
+  for index in `seq 1 $countatoms`
+  do 
+    nguessA=`echo $guessatoms | awk -v var=$index '{print $var}'`
+    nguessN=`echo $guessnums  | awk -v var=$index '{print $var}'`
+    eval "if [ -z \"\$$nguessA\" ]; then echo wrong innput [EXITING]; exit; fi"
+    eval "nowN=\`echo \$$nguessA\`"
+    maximum=`echo $nowN/$nguessN | bc`
+    if [ -z "$min" ]
+    then
+      min=$maximum
+    else
+      if [ $maximum -lt $min ]
+      then
+        min=$maximum
+      fi 
+    fi
+  done
+  if [ -z "$min" ]
+  then
+    echo 0
+  else 
+    echo $min 
+  fi
+}
+
+function removemol {
+  guessatoms=`echo $1 | sed "s/[0-9]/ /g"`
+  guessnums=` echo $1 | sed "s/[a-z]/ /g" | sed "s/[A-Z]/ /g"` 
+  #check size
+  countatoms=`echo $guessatoms |  xargs -n 1 |  wc -l`
+  countnums=`echo  $guessnums  |  xargs -n 1 |  wc -l`
+  if [ $countatoms -ne $countnums ]
+  then
+    echo "JKname: Wrong input: $1 [EXITING]"
+    exit
+  fi
+  for index in `seq 1 $countatoms`
+  do
+    nguessA=`echo $guessatoms | awk -v var=$index '{print $var}'`
+    nguessN=`echo $guessnums  | awk -v var=$index '{print $var}'`
+    eval "nowN=\`echo \$$nguessA\`"
+    newvalue=`echo $nowN-$2*$nguessN | bc`
+    eval "$nguessA=$newvalue"
+  done    
+}
+
+###########################################################
+
+#checking for files input
 if [ -z "$files" ]
 then
   if [ $Qlog -eq 1 ]
@@ -69,6 +159,7 @@ then
   fi
 fi
 
+#going through all files
 #echo FILES = $files
 for file in $files
 do
@@ -81,143 +172,106 @@ do
     fileXYZ=`basename $file .xyz`.xyz
   fi
   
-  atoms=`cat $fileXYZ | awk '{print $1}' | xargs`
-  
-  C=0
-  S=0
-  O=0
-  H=0
-  N=0
-  Na=0
-  Cl=0
+  lines=`wc -l $fileXYZ | awk '{print $1}'`
+  lines=`echo $lines-2 | bc`
+  atoms=`cat $fileXYZ | tail -n $lines | awk '{print $1}' | xargs`
 
+  #initation some atoms + those in  the input file
+  for i in Na Cl C N O S H
+  do
+    eval "$i=0"
+  done 
   for i in $atoms
   do
-    case $i in 
-    "Na") Na=`echo $Na + 1 | bc` 
-         ;;
-    "Cl") Cl=`echo $Cl + 1 | bc` 
-         ;;
-    "C") C=`echo $C + 1 | bc` 
-         ;;
-    "S") S=`echo $S + 1 | bc` 
-         ;;
-    "O") O=`echo $O + 1 | bc` 
-         ;;
-    "H") H=`echo $H + 1 | bc` 
-         ;;
-    esac
+    eval "if [ -z \"\$$i\" ]; then $i=0; fi"
+    eval "$i=\`echo \$$i+1 | bc\`"
+  done
+
+  #printing summary name
+  uatoms=`echo $atoms | xargs -n 1 | sort -u | xargs` 
+  for i in $uatoms
+  do
+    eval "printf \"\$i\${$i}\""
+  done
+  printf " $fileXYZ"
+  printf "\n"
+
+  output="" 
+  #going through some user innputs
+  if [ -z "$usermolecules" ]
+  then 
+    size=0
+  else
+    size=`echo $usermolecules  | xargs -n 1 | wc -l`  
+  fi
+  if [ $size -gt 0 ]
+  then
+    for index in `seq 1 $size`
+    do
+      usermolecule=`echo $usermolecules | awk -v var=$index '{print $var}'`
+      usermoleculeN=`echo $usermoleculesN | awk -v var=$index '{print $var}'`
+      amount=`molcheck $usermolecule`
+      re='^[0-9]+$'
+      if ! [[ "$amount" =~ $re ]] ; then
+        echo "ERROR in molecules $usermolecule (see JKname -help) [EXITING]"
+        exit
+      fi 
+      if [ $amount -gt 0 ]
+      then
+        removemol $usermolecule $amount
+        echo "$usermoleculeN = $amount"
+        output+="$amount$usermoleculeN"
+      fi
+    done
+  fi
+  predefinedmolecules=" 10Na10Cl C4O1H10 C10O8H16 S1O3C1H4 H2S1O4 C1O2 C1N3H5 C2N1H7 N1H3 H2O1 H1"
+  predefinedmoleculesN="seed     buoh    hom      msa      sa     coo  gd     dma    am   aq   p"
+  size=`echo $predefinedmolecules | xargs -n 1 | wc -l`
+  for index in `seq 1 $size`
+  do
+    predefinedmolecule=`echo $predefinedmolecules | awk -v var=$index '{print $var}'`
+    predefinedmoleculeN=`echo $predefinedmoleculesN | awk -v var=$index '{print $var}'`
+    amount=`molcheck $predefinedmolecule`
+    re='^[0-9]+$'
+    if ! [[ "$amount" =~ $re ]] ; then
+      echo "ERROR in molecules $predefinedmolecule [EXITING]"
+      exit
+    fi 
+    if [ $amount -gt 0 ]
+    then
+      removemol $predefinedmolecule $amount
+      echo "$predefinedmoleculeN = $amount"
+      output+="$amount$predefinedmoleculeN"
+    fi
   done
   
-  echo Na${Na}Cl${Cl}C${C}N${N}O${O}S${S}H${H}
+  #printing the rest of files
+  uatoms=`echo $atoms | xargs -n 1 | sort -u | xargs` 
+  sum=0
+  for i in $uatoms
+  do
+    eval "sum=\`echo $sum+\${$i} | bc\`"
+    eval "printf \"\$i\${$i}\""
+  done
+  if [ $sum -ne 0 ]
+  then
+    printf " -- stil $sum remaining atoms (check JKname -help and use option -mol) [SKIPPING]\n"
+    continue
+  fi
+  printf "\n"
 
-  # NaCl seed
-  seed=0
-  if [ $Na -ge 1 ] && [ $Cl -ge 1 ]
-  then
-    seed=1
-    Na=0
-    Cl=0
-  fi 
-  # BuOH
-  buoh=0
-  if [ $Qbuoh -ge 1 ] && [ $C -ge 1 ]
-  then
-    buoh=`echo $C/4 | bc`
-    C=0
-    O=`echo $O-1*$buoh | bc`
-    H=`echo $H-10*$buoh | bc`
-  fi
-  # HOM
-  hom=0
-  if [ $Qhom -ge 1 ] && [ $C -ge 10 ]
-  then
-    if [ $C -ge 20 ]
-    then
-      hom=2
-    else
-      hom=1
-    fi
-    C=`echo $C-10*$hom | bc`
-    O=`echo $O-8*$hom | bc`
-    H=`echo $H-16*$hom | bc`
-  fi
-  # MSA ... no MSAm
-  msa=0
-  if [ $Qmsa -ge 1 ] && [ $C -ge 1 ] && [ $S -ge 1 ]
-  then
-    msa=`echo $C | bc` 
-    C=`echo $C-$msa | bc`
-    S=`echo $S-$msa | bc`
-    O=`echo $O-3*$msa | bc`
-    H=`echo $H-4*$msa | bc`
-  fi
-  # H2SO4
-  sam=0
-  sa=$S
-  O=`echo $O-4*$sa | bc`
-  H=`echo $H-2*$sa | bc`
-  S=`echo $S-$sa | bc`
-
-  # CO2 if just C and O are present
-  co2=0
-  if [ $C -gt 0 ] && [ $O -gt 0 ] && [ $N -eq 0 ] && [ $H -eq 0 ]
-  then
-    co2=$C
-    C=`echo $C-$co2 | bc`
-    O=`echo $O-2*$co2 | bc`
-  fi  
-  
-  if (( $(echo "$N > $C" |bc -l) ))
-  then
-  # GD = C1N3H5
-    dma=0
-    gd=$C
-    H=`echo $H-5*$gd | bc`
-    N=`echo $N-3*$gd | bc`
-    C=`echo $C-1*$gd | bc`
-  else
-  # DMA = C2N1H7
-    gd=0
-    dma=$N
-    H=`echo $H-7*$dma | bc`
-    N=`echo $N-1*$dma | bc`
-    C=`echo $C-2*$dma | bc`
-  fi
-
-  # A = NH3
-    am=$N
-    H=`echo $H-3*$am | bc`
-    N=`echo $N-1*$am | bc`
-  
-  # W = H2O
-    aq=$O
-    H=`echo $H-2*$aq | bc`
+  ## proton
+  #  p=$H
+  #  if [ $p -eq -1 ]
+  #  then
+  #    sam=1
+  #    sa=`echo $sa-1 | bc`
+  #    H=0
+  #  else
+  #    H=`echo $H-1*$p | bc`
+  #  fi
  
-  # proton
-    p=$H
-    if [ $p -eq -1 ]
-    then
-      sam=1
-      sa=`echo $sa-1 | bc`
-      H=0
-    else
-      H=`echo $H-1*$p | bc`
-    fi
- 
-  echo C${C}N${N}O${O}S${S}H${H}
-  name=""
-  if [ $seed -gt 0 ]; then echo seed = $seed;name+="${seed}seed"; fi
-  if [ $buoh -gt 0 ]; then echo buoh = $buoh;name+="${buoh}buoh"; fi
-  if [ $msa  -gt 0 ]; then echo msa  = $msa ;name+="${msa}msa"; fi
-  if [ $sa   -gt 0 ]; then echo sa   = $sa  ;name+="${sa}sa"; fi
-  if [ $sam  -gt 0 ]; then echo sam  = $sam ;name+="${sam}sam"; fi
-  if [ $gd   -gt 0 ]; then echo gd   = $gd  ;name+="${gd}gd"; fi
-  if [ $dma  -gt 0 ]; then echo dma  = $dma ;name+="${dma}dma"; fi
-  if [ $am   -gt 0 ]; then echo am   = $am  ;name+="${am}am"; fi
-  if [ $aq   -gt 0 ]; then echo aq   = $aq  ;name+="${aq}aq"; fi
-  if [ $p    -gt 0 ]; then echo p    = $p   ;name+="${p}p"; fi
-  
+  name=$output
   if [ "$fileXYZ" != "$name.xyz" ]
   then
     name0=$name
